version: '3.8'

services:
  mssql:
    networks:
      default_net:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: root@@@123  
      ACCEPT_EULA: Y
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  mssql_data:  
   
networks:
  default_net:
    external: true