version: "3.7"

x-service-common:
  &service-common
  networks:
    default_net:
  restart: on-failure:3

services:
  mysql:
    <<: *service-common
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      
  zookeeper:
    <<: *service-common
    user: root
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "2181:2181" 
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - ./data/zookeeper:/tmp/zookeeper  
    environment:
      - KAFKA_HOME=${KAFKA_HOME}
    command: "${KAFKA_HOME}/bin/zookeeper-server-start.sh ${KAFKA_HOME}/config/zookeeper.properties"

  kafka:
    <<: *service-common
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka  
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_HOME=${KAFKA_HOME}
    user: root
    volumes:
      - ./data/kafka_logs:/etc/logs
      - ./config/server.properties:${KAFKA_HOME}/config/server.properties:ro
    command: ${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/server.properties
    restart: on-failure:3
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-connect:
    <<: *service-common
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "8083:8083"
    hostname: kafka-connect
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - KAFKA_HOME=${KAFKA_HOME}
    volumes:
      - ./config/inventory-mysql-kafka-connect.properties:${KAFKA_HOME}/config/inventory-mysql-kafka-connect.properties:ro
      - ./config/server.properties:${KAFKA_HOME}/config/server.properties:ro
      - ./config/connect-standalone.properties:${KAFKA_HOME}/config/connect-standalone.properties:ro
      - ./jars/debezium-connector-mysql:${KAFKA_HOME}/libs/debezium-connector-mysql
    command: "${KAFKA_HOME}/bin/connect-standalone.sh ${KAFKA_HOME}/config/connect-standalone.properties ${KAFKA_HOME}/config/inventory-mysql-kafka-connect.properties"

volumes:
  mysql_data:
  broker:
   
networks:
  default_net:
    external: true
